### ISSUE TITLE
TypeError: Cannot read property 'device' of undefined

### ISSUE THREAD

**Issue by Krenath** [donavanbecker/homebridge-wemo#9]
Just started getting this today:

Mar 13 19:18:35 raspberrypi homebridge[321]: events.js:141
Mar 13 19:18:35 raspberrypi homebridge[321]: throw er; // Unhandled 'error' event
Mar 13 19:18:35 raspberrypi homebridge[321]: ^
Mar 13 19:18:35 raspberrypi homebridge[321]: TypeError: Cannot read property 'device' of undefined
Mar 13 19:18:35 raspberrypi homebridge[321]: at /usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/wemo.js:28:31
Mar 13 19:18:35 raspberrypi homebridge[321]: at Parser.<anonymous> (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/node_modules/xml2js/lib/xml                  2js.js:483:18)
Mar 13 19:18:35 raspberrypi homebridge[321]: at emitOne (events.js:77:13)
Mar 13 19:18:35 raspberrypi homebridge[321]: at Parser.emit (events.js:169:7)
Mar 13 19:18:35 raspberrypi homebridge[321]: at Object.onclosetag (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/node_modules/xml2js/lib/xml2                  js.js:444:26)
Mar 13 19:18:35 raspberrypi homebridge[321]: at emit (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/node_modules/xml2js/node_modules/sax/lib/                  sax.js:639:35)
Mar 13 19:18:35 raspberrypi homebridge[321]: at emitNode (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/node_modules/xml2js/node_modules/sax/                  lib/sax.js:644:5)
Mar 13 19:18:35 raspberrypi homebridge[321]: at closeTag (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/node_modules/xml2js/node_modules/sax/                  lib/sax.js:903:7)
Mar 13 19:18:35 raspberrypi homebridge[321]: at Object.write (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/node_modules/xml2js/node_modules/                  sax/lib/sax.js:1436:13)
Mar 13 19:18:35 raspberrypi homebridge[321]: at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/node_                  modules/xml2js/lib/xml2js.js:502:31)
Mar 13 19:18:35 raspberrypi homebridge[321]: at Parser.parseString (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/node_modules/xml2js/lib/xml                  2js.js:7:59)
Mar 13 19:18:35 raspberrypi homebridge[321]: at Object.exports.parseString (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/node_modules/xml2js                  /lib/xml2js.js:534:19)
Mar 13 19:18:35 raspberrypi homebridge[321]: at Request._callback (/usr/local/lib/node_modules/homebridge-wemo/node_modules/wemo/wemo.js:26:12)
Mar 13 19:18:35 raspberrypi homebridge[321]: at Request.self.callback (/usr/local/lib/node_modules/homebridge-wemo/node_modules/request/request.js:198:22)
Mar 13 19:18:35 raspberrypi homebridge[321]: at emitTwo (events.js:87:13)
Mar 13 19:18:35 raspberrypi homebridge[321]: at Request.emit (events.js:172:7)

**Comment by rudders** [comment]
Have you updated anything recently? Including Wemo firmware - I noticed an update to wemo firmware in the last day or so.

**Comment by Krenath** [comment]
I didn't update anything intentionally.  As far as I'm aware, I hadn't even restarted my Homebridge until it stopped responding on its own about roughly 2-3 hours ago.

**Comment by Krenath** [comment]
This error that it throws, it doesn't throw until it receives a response back from the last configured device.  Once it sees the last device respond, it throws this error and dies. (And since I have it configured as a service, it eventually restarts and goes through it all again

**Comment by rudders** [comment]
Can you post you config.json so I can see the device configuration.
